### ISSUE TITLE
porkbun api update

### ISSUE THREAD

**Issue by apisashla** [caddy-dns/porkbun#18]
I've been getting emails from Porkbun indicating their API endpoint has updated from `porkbun.com` to `api.porkbun.com.` 

Wasn't able to find a direct reference to the endpoint in the module, otherwise I'd just submit a PR - are we waiting on an upstream package, and if so, which?

**Comment by Niallfitzy1** [comment]
This was fixed already in https://github.com/caddy-dns/porkbun/pull/17

**Comment by apisashla** [comment]
Noted! Thought I had the current package version, maybe not. Closing, and thanks! Edit: you beat me to it, appreciate the clarification
