### ISSUE TITLE
libdns/porkbun needs update to v0.2.0 to continue working with porkbun API.

### ISSUE THREAD

**Issue by brusson** [caddy-dns/porkbun#19]
Porkbun is changing their API endpoint and disabling the old endpoint on 2024-12-01. The endpoint has been already been updated in libdns/porkbun v0.2.0. This project needs to switch to that version.

**Comment by Niallfitzy1** [comment]
This was fixed already in https://github.com/caddy-dns/porkbun/pull/17 (Release 0.20 of this module)

I've updated the readme to flag that this is handled in the recent versions.

**Comment by brusson** [comment]
Thanks! I must have missed that commit when I was checking if it had been done already.
